apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-health-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: "arch.homework"
    http:
      paths:
      - path: /(health)
        pathType: Prefix
        backend:
          service:
            name: health-app-service
            port:
              number: 8030
      - path: /otusapp/.*/(health)
        pathType: ImplementationSpecific
        backend:
          service:
            name: health-app-service
            port:
              number: 8030
        